# Generated by Django 4.1.4 on 2023-08-12 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_name', models.CharField(max_length=25)),
                ('s_age', models.IntegerField(max_length=3)),
                ('s_class', models.CharField(max_length=15)),
                ('s_email', models.EmailField(max_length=25)),
            ],
        ),
    ]
