# Generated by Django 4.2.4 on 2023-08-14 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentregister',
            name='s_password',
            field=models.CharField(default=123, max_length=8),
            preserve_default=False,
        ),
    ]
