# Generated by Django 4.2.4 on 2023-08-15 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0002_studentregister_s_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentregister',
            name='s_reg',
            field=models.IntegerField(auto_created=True, default=123, max_length=5),
            preserve_default=False,
        ),
    ]
