# Generated by Django 4.2.4 on 2023-08-15 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0004_alter_studentregister_s_reg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentregister',
            name='id',
        ),
        migrations.AlterField(
            model_name='studentregister',
            name='s_reg',
            field=models.AutoField(auto_created=True, db_index=True, max_length=5, primary_key=True, serialize=False),
        ),
    ]
