# Generated by Django 4.1.4 on 2023-09-13 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0006_staff_remove_studentregister_s_age_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentregister',
            name='s_section',
            field=models.CharField(default='c', max_length=3),
            preserve_default=False,
        ),
    ]
