# Generated by Django 4.1.4 on 2023-09-13 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0007_studentregister_s_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentregister',
            name='s_grade',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studentregister',
            name='s_feedue',
            field=models.DecimalField(decimal_places=2, default=1000, max_digits=10),
        ),
    ]
