# Generated by Django 4.2.4 on 2023-09-15 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0008_studentregister_s_grade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='staff_email',
            field=models.EmailField(default='example@gmail.com', max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staff',
            name='staff_password',
            field=models.CharField(default='123', max_length=8),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studentregister',
            name='s_attendance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='studentregister',
            name='s_feedue',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=10),
        ),
        migrations.AlterField(
            model_name='studentregister',
            name='s_grade',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=5),
        ),
    ]
